const AboutPage = () => {
  return (
    <main>
      <h1>About</h1>
      <p>Honestly? With all the shit going on in the world along with the impossibility of travel and lack of interpersonal connection, Bleak Narrative was created with the intent to bring us together through music, visual arts, storytelling, and our love for the underground club culture. Some might say that doing things like these remotely defeats its purpose. They might say that raving and clubbing should be a communal, physical thing that uses spaces to create bonds while listening to incredible music. Obviously, this is entirely true, and we all miss these moments. Still, we couldn't stay idle and do nothing; if this platform fills even a tiny little gap left in our scene by bringing people to share their talent, we've fulfilled our purpose!</p>
      <p>The crew will bring and curate content for the platform and its social channels. If you're enjoying what you're reading and feel like participating, don't hesitate to contact us. You don't need to have thousands of followers, play vinyl, or wear black all the time! As long as you're passionate and want to have your content shared, we got you. We're all about making connections and partnerships, and we're sure that one day we'll all meet in person and throw a three-day rave. Fingers crossed.</p>
      <p>As much as we love to poke fun at the scene (we really do), we still do it with respect and don't tolerate offensive content. Remember, this culture was built by Black and Latino queers back in the day when creating safe spaces was not only a matter of expression but necessity and survival. Having said that, we want to keep this space open for everyone, but we'll always give the front line to minorities and underrepresented groups. Being members of the LGBTQI+ group ourselves, we reserve the right to give preference to certain folks.</p>
      <p>2020 has been tough on us in many (if not all) aspects of all our lives, the nightlife being one of them. We still want to raise the question: what positive thing could come out of an otherwise "lost" year? We endure sadness and despair every day, but we still aspire to use this time to be creative and actually do something meaningful. We're not sure how meaningful this is or until when it's going to last. We're not sure if people will want to participate and engage. A stranger said something on Reddit that, despite our doubts, encouraged us to pursue this project. They wrote: "Times of uncertainty can be springboards for the greatest of creative movements." We decided to take their advice and go with it. So, that's the story of how much of an impact a stranger's word on the WWW could have on us (btw, if you ever read this, give us a shout out!). It's this kind of positive impact we want Bleak Narrative to have. Maybe when all is back to normal, and the dance floors are filled with sweaty bodies again, this platform will become anachronic; it will have served its purpose. Or perhaps it will stay alive, we can't be sure. The future is uncertain, but the present is now. OH NO, we're getting all cheesy and cliche. Ok, back to silly, pretentious, artsy pricks who think they're being so original! Hope to see you around.</p>
      <p><strong>The Bleak Narrative Crew</strong></p>
    </main>
  )
}

export default AboutPage
